using System.Collections.Generic;
using System.Linq;

public static class LanguageData
{
    public static readonly List<Dictionary<string, string>> Texts = new List<Dictionary<string, string>>
    {
        new Dictionary<string, string> { { "ko", "설정" }, { "jp", "設定" }, { "en", "Settings" } },
        new Dictionary<string, string> { { "ko", "플레이어 이름" }, { "jp", "プレイヤー名" }, { "en", "Player Name" } },
        new Dictionary<string, string> { { "ko", "서버 ID" }, { "jp", "サーバーID" }, { "en", "Server ID" } },
        new Dictionary<string, string> { { "ko", "항상 위에 표시" }, { "jp", "常に上に表示" }, { "en", "Always on Top" } },
        new Dictionary<string, string> { { "ko", "클릭 시 채팅창 표시" }, { "jp", "クリック時チャット画面表示" }, { "en", "Show Chatbox on Click" } },

        new Dictionary<string, string> { { "ko", "이미지 보내기" }, { "jp", "画像情報を送る" }, { "en", "Send Image Info" } },



        
        new Dictionary<string, string> { { "ko", "언어" }, { "jp", "言語" }, { "en", "Language" } },
        new Dictionary<string, string> { { "ko", "음성인식" }, { "jp", "音声認識" }, { "en", "Speech Recognition" } },
        new Dictionary<string, string> { { "ko", "음성인식" }, { "jp", "音声認識" }, { "en", "Speech Recognition" } }, // "Speech R."
        new Dictionary<string, string> { { "ko", "사전로딩" }, { "jp", "先読み" }, { "en", "Preloading" } },
        new Dictionary<string, string> { { "ko", "기타" }, { "jp", "その他" }, { "en", "Extra" } },
        new Dictionary<string, string> { { "ko", "작고 빠른(X16)" }, { "jp", "小さくて速い(X16)" }, { "en", "Small, Fast (X16)" } },
        new Dictionary<string, string> { { "ko", "기본(X8)" }, { "jp", "基本(X8)" }, { "en", "Basic (X8)" } },
        new Dictionary<string, string> { { "ko", "크고 정확한(X3)" }, { "jp", "大きくて正確(X3)" }, { "en", "Large, Accurate (X3)" } },
        new Dictionary<string, string> { { "ko", "더 크고 정확한(X1)" }, { "jp", "より大きく、より正確(X1)" }, { "en", "Larger, More Accurate (X1)" } },
        new Dictionary<string, string> { { "ko", "다운로드" }, { "jp", "ダウンロード" }, { "en", "Download" } },
        new Dictionary<string, string> { { "ko", "테스트" }, { "jp", "テスト" }, { "en", "Test" } },
        new Dictionary<string, string> { { "ko", "음성 인식용 모듈 다운로드" }, { "jp", "音声認識用モジュールダウンロード" }, { "en", "Download modules for speech recognition" } },
        new Dictionary<string, string> { { "ko", "음성" }, { "jp", "音声" }, { "en", "Voice" } },
        new Dictionary<string, string> { { "ko", "프로그램 구동시 모듈을 미리 읽어서,\n최초 동작을 빠르게 합니다." }, { "jp", "プログラム駆動時モジュールを先読みして、\n初期動作を高速化します。" }, { "en", "Preloads modules when the program is run,\nspeeding up first-time behavior." } },
        new Dictionary<string, string> { { "ko", "메인 캐릭터의 음성 모듈을 미리 읽어옵니다." }, { "jp", "メインキャラクターの音声モジュールを先読みます。" }, { "en", "Preload main character's voice module." } },
        new Dictionary<string, string> { { "ko", "설정된 음성 인식 모듈을 미리 읽어옵니다." }, { "jp", "設定された音声認識モジュールを先読みます。" }, { "en", "Preload set speech recognition module." } },
        new Dictionary<string, string> { { "ko", "다운로드" }, { "jp", "ダウンロード" }, { "en", "Downloaded" } },
        new Dictionary<string, string> { { "ko", "확인" }, { "jp", "確認" }, { "en", "Confirm" } },
        new Dictionary<string, string> { { "ko", "작업 성공" }, { "jp", "作業成功" }, { "en", "Task Success" } },
        new Dictionary<string, string> { { "ko", "다운로드 받으시겠습니까?" }, { "jp", "ダウンロードしますか？" }, { "en", "Do you want to download?" } },
        new Dictionary<string, string> { { "ko", "의 용량이 필요합니다.\n" }, { "jp", "の容量が必要です。\n" }, { "en", "of space is required.\n" } },
        new Dictionary<string, string> { { "ko", "]이 Workspace에 무사히 추가되었습니다.\nInworld Name에 반영하시겠습니까?" }, { "jp", "]がWorkspaceに無事追加されました.\nInworld Nameに反映しますか？" }, { "en", "] have been successfully added to Workspace.\nDo you want to reflect to your [Inworld Name]?" } },
        new Dictionary<string, string> { { "ko", "현재 목소리 설정을 저장하시겠습니까?" }, { "jp", "現在の音声設定を保存しますか？" }, { "en", "Do you want to save your current voice settings?" } },
        new Dictionary<string, string> { { "ko", "정말 삭제하시겠습니까?" }, { "jp", "本当に削除しますか？" }, { "en", "Do you really want to delete it?" } },
        new Dictionary<string, string> { { "ko", "음성생성에 GPU 가속을 지금 바로 적용하시겠습니까?" }, { "jp", "音声生成にGPU加速を今すぐ適用してみますか？" }, { "en", "Want to enable GPU acceleration to voice generation right now?" } },
        new Dictionary<string, string> { { "ko", "음성인식을 바로 활성화 하시겠습니까?" }, { "jp", "音声認識を今すぐ適用してみますか？" }, { "en", "Want to enable voice recognition right now?" } },
        new Dictionary<string, string> { { "ko", "취소" }, { "jp", "キャンセル" }, { "en", "Cancel" } },
        new Dictionary<string, string> { { "ko", "완료" }, { "jp", "完了" }, { "en", "Finish" } },
        new Dictionary<string, string> { { "ko", "에러" }, { "jp", "エラー" }, { "en", "Error" } },
        new Dictionary<string, string> { { "ko", "안내" }, { "jp", "案内" }, { "en", "Guidance" } },
        new Dictionary<string, string> { { "ko", "작업이 취소되었습니다." }, { "jp", "作業は中止されました。" }, { "en", "The task was canceled." } },
        new Dictionary<string, string> { { "ko", "작업이 완료되었습니다." }, { "jp", "作業が完了しました。" }, { "en", "The task is completed." } },
        new Dictionary<string, string> { { "ko", "이미 다운로드 중인 파일이 있습니다." }, { "jp", "すでにダウンロード中のファイルがあります。" }, { "en", "You already have a downloading file." } },
        new Dictionary<string, string> { { "ko", "이미 해당 이름을 갖는 캐릭터가 있습니다." }, { "jp", "すでにその名前を持つキャラクターがあります。" }, { "en", "There is already a character with that name." } },
        new Dictionary<string, string> { { "ko", "창을 닫을 때 적용됩니다." }, { "jp", "ウィンドウ終了時に適用されます。" }, { "en", "It will be applied at closing the window." } },
        new Dictionary<string, string> { { "ko", "현재 버전은 Inworld와 Local만 제공합니다." }, { "jp", "現在のバージョンは[Inworld, Local]のみ提供しています。" }, { "en", "Current version only offers Inworld and Local." } },
        new Dictionary<string, string> { { "ko", "현재 버전은 Local만 제공합니다." }, { "jp", "現在のバージョンは[Local]のみ提供しています。" }, { "en", "Current version only offers Local." } },
        new Dictionary<string, string> { { "ko", "다음 중 하나의 값이 정확하지 않습니다.\n[Workspace 이름]\n[inworld api key(Workspace용)]\n[Inworld Name]" }, { "jp", "次のいずれかのデータが正しくありません。\n[Workspace名]\n[inworld api key(Workspace用)]\n[Inworld Name]" }, { "en", "One of the following values is incorrect\n[Workspace]\n[API Key(for workspace)]\n[Inworld Name]" } },
        new Dictionary<string, string> { { "ko", "우선 Studio API KEY를 입력해주세요." }, { "jp", "まず、Studio API KEYを入力してください。" }, { "en", "Enter your Studio API KEY first." } },
        new Dictionary<string, string> { { "ko", "에 저장하였습니다." }, { "jp", "に保存しました。" }, { "en", " : save location" } },
        new Dictionary<string, string> { { "ko", "inworld 폴더의 하위 위치에만 저장할 수 있습니다." }, { "jp", "inworldフォルダのサブロケーションにのみ保存できます。" }, { "en", "You can only save to a sublocation of the inworld folder." } },
        new Dictionary<string, string> { { "ko", "다음 중 하나의 값이 정확하지 않습니다.\n[Workspace]\n[Inworld Name]\n[Studio API KEY]" }, { "jp", "次のいずれかのデータが正しくありません。\n[Workspace]\n[Inworld Name]\n[Studio API KEY]" }, { "en", "One of the following values is incorrect.\n[Workspace]\n[Inworld Name]\n[Studio API KEY]" } },
        new Dictionary<string, string> { { "ko", "이름을 입력해주세요." }, { "jp", "名前を入力してください。" }, { "en", "Please enter a name." } },
        new Dictionary<string, string> { { "ko", "json 파일이 정상적이지 않습니다." }, { "jp", "jsonファイルが正常ではありません。" }, { "en", "The JSON file is not valid." } },
        new Dictionary<string, string> { { "ko", "json 파일을 선택해주세요." }, { "jp", "jsonファイルを選択してください。" }, { "en", "Select a JSON file." } },
        new Dictionary<string, string> { { "ko", "main.exe 하위 폴더에만 저장할 수 있습니다." }, { "jp", "main.exeサブフォルダにのみ保存できます。" }, { "en", "You can only store them in the main.exe subfolder." } },
        new Dictionary<string, string> { { "ko", "]으로 캐릭터를 변경하시겠습니까?" }, { "jp", "]にキャラクターを変更しますか？" }, { "en", "] : Change Character" } },
        new Dictionary<string, string> { { "ko", "\n'AI'가 설정되지 않았습니다." }, { "jp", "\n'AI'が設定されていません。" }, { "en", "\nNo 'AI' is set up." } },
        new Dictionary<string, string> { { "ko", "\n'Animation assets'가 설정되지 않았습니다." }, { "jp", "\n'Animation assets'が設定されていません。" }, { "en", "\nNo 'Animation assets' is set up." } },
        new Dictionary<string, string> { { "ko", "\n'Voice'가 설정되지 않았습니다." }, { "jp", "\n'Voice'が設定されていません。" }, { "en", "\nNo 'Voice' is set up." } },
        new Dictionary<string, string> { { "ko", "]으로 메인 캐릭터를 변경하였습니다." }, { "jp", "]にメインキャラクターを変更しました。" }, { "en", "] : Change Main Character" } },
        new Dictionary<string, string> { { "ko", "[arona]는 삭제할 수 없습니다." }, { "jp", "[arona]は削除できません。" }, { "en", "You cannot delete [arona]." } },
        new Dictionary<string, string> { { "ko", "메인 캐릭터는 삭제할 수 없습니다." }, { "jp", "メインキャラクターは削除できません。" }, { "en", "You cannot delete the main character." } },
        new Dictionary<string, string> { { "ko", "유효한 키가 아니거나, 통신 상태가 좋지 않습니다." }, { "jp", "有効なキーでないか、通信状態が悪いです。" }, { "en", "The key is not valid, or the connection is poor." } },
        new Dictionary<string, string> { { "ko", "[설정]에서 Voice를 [GPU]로 설정해주세요." }, { "jp", "[設定]でVoiceを[GPU]に設定してください。" }, { "en", "Set Voice to [GPU] in [Settings]." } },
        new Dictionary<string, string> { { "ko", "GPU 가속을 사용할 수 없는 컴퓨터입니다." }, { "jp", "GPU加速を使用できないコンピュータです。" }, { "en", "The computer is not capable of GPU acceleration." } },
        new Dictionary<string, string> { { "ko", "GPU 가속을 활성화하였습니다." }, { "jp", "GPU加速を起動しました。" }, { "en", "GPU acceleration is enabled." } },
        new Dictionary<string, string> { { "ko", "[설정]에서 Talk을 설정해주세요." }, { "jp", "[設定]でTalkを設定してください。" }, { "en", "Set up Talk in [Settings]." } },
        new Dictionary<string, string> { { "ko", "이미 음성인식이 활성화 되어있습니다." }, { "jp", "すでに音声認識が起動しています。" }, { "en", "Speech recognition is already enabled." } },
        new Dictionary<string, string> { { "ko", "마이크가 감지되지 않습니다." }, { "jp", "マイクが検知されません。" }, { "en", "The microphone is not detected." } },
        new Dictionary<string, string> { { "ko", "음성 인식을 활성화하였습니다." }, { "jp", "音声認識を起動しました。" }, { "en", "Speech recognition is enabled." } },
        new Dictionary<string, string> { { "ko", "음성 인식이 활성화되지 않았습니다." }, { "jp", "音声認識が起動されません。" }, { "en", "Speech recognition is not enabled." } },
        new Dictionary<string, string> { { "ko", "음성인식을 비활성화하였습니다." }, { "jp", "音声認識を非アクティブ化しました。" }, { "en", "Speech recognition is disabled." } },
        new Dictionary<string, string> { { "ko", "[enter]는 사용하실 수 없습니다." }, { "jp", "[enter]は使用できません。" }, { "en", "key [ENTER] is not allowed." } },
        new Dictionary<string, string> { { "ko", "충돌 방지를 위해 [대화] 옵션을 OFF로 설정하세요." }, { "jp", "衝突を防ぐため、[会話]オプションをOFFにしてください。" }, { "en", "Please set [Talk] Option to OFF to avoid conflicts." } },
        new Dictionary<string, string> { { "ko", "새로운 대화를 시작하겠습니까?" }, { "jp", "新しい会話を始めますか？" }, { "en", "Do you want to start a new conversation?" } },
        new Dictionary<string, string> { { "ko", "네" }, { "jp", "はい" }, { "en", "Yes" } },
        new Dictionary<string, string> { { "ko", "아니오" }, { "jp", "いいえ" }, { "en", "No" } },
        new Dictionary<string, string> { { "ko", "이름" }, { "jp", "名前" }, { "en", "Name" } },
        new Dictionary<string, string> { { "ko", "입력" }, { "jp", "入力" }, { "en", "Input" } },
        new Dictionary<string, string> { { "ko", "변경" }, { "jp", "変更" }, { "en", "Change" } },
        new Dictionary<string, string> { { "ko", "초기화" }, { "jp", "初期化" }, { "en", "Initialize" } },
        new Dictionary<string, string> { { "ko", "무료" }, { "jp", "無料" }, { "en", "Free" } },
        new Dictionary<string, string> { { "ko", "있음" }, { "jp", "あり" }, { "en", "Exist" } },
        new Dictionary<string, string> { { "ko", "선택" }, { "jp", "選択" }, { "en", "Select" } },
        new Dictionary<string, string> { { "ko", "카탈로그" }, { "jp", "カタログ" }, { "en", "Catalog" } },
        new Dictionary<string, string> { { "ko", "Inworld에서 사용할 캐릭터가 포함된 Workspace를 골라주세요." }, { "jp", "Inworldで使用するキャラクターが含まれているWorkspaceを選択してください。" }, { "en", "Select the Inworld Workspace that contains the characters you want to use." } },
        new Dictionary<string, string> { { "ko", "Workspace에 맞는 API Key를 골라주세요.\n(Workspace마다 API Key가 다릅니다.)" }, { "jp", "Workspaceに合ったAPI Keyを選択してください。\n(WorkspaceごとにAPI Keyが異なります)" }, { "en", "Choose an API Key that matches your Workspace.\n(Each Workspace has a different API Key)" } },
        new Dictionary<string, string> { { "ko", "사용할 캐릭터가 Inworld에 등록된 이름" }, { "jp", "使用するキャラクターがInworldに登録されている名前" }, { "en", "Name of the character registered in Inworld." } },
        new Dictionary<string, string> { { "ko", "animation 폴더에서 캐릭터가 사용할 애니메이션을 골라주세요." }, { "jp", "animationフォルダからキャラクターが使用するアニメーションを選択してください。" }, { "en", "Select the animation you want the character to use from the animation folder." } },
        new Dictionary<string, string> { { "ko", "idle : 평소\nsit : 앉기\npick : 집기\nfall : 낙하 (pick)\nthink : 채팅 입력\ntalk : 채팅 답변\nsmile : 설정(think)\nwalk : 걷기\n\n(해당 동작 애니메이션이 없을 경우, 괄호 속 애니메이션이 사용됩니다. \n그래도 사용할 애니메이션이 없으면 idle 애니메이션이 사용됩니다.)" }, { "jp", "idle : 通常\nsit : 座る\npick : つまみ\nfall : 落下(pick)\nthink : チャット入力\ntalk : チャット発言\nsmile : 設定(think)\nwalk : 歩く\n\n(該当する動作アニメーションがない場合、括弧内のアニメーションが使用されます。\nそれでも使用するアニメーションがない場合は、idleアニメーションが使用されます。)" }, { "en", "idle: idle\nsit: sitting\npick: picking up\nfall: falling (pick)\nthink: chat typing\ntalk: chat answer\nsmile: setting (think)\nwalk: walk\n\n(If there is no corresponding action animation, the animation in parentheses is used. \nIf there is still no animation to use, the idle animation is used.)" } },
        new Dictionary<string, string> { { "ko", "현재 애니메이션 사용 여부\n(idle은 해제할 수 없습니다.)" }, { "jp", "現在のアニメーションの使用有無\n(idleは解除できません。)" }, { "en", "Whether the current animation is enabled or disabled.\n(idle cannot be turned off)" } },
        new Dictionary<string, string> { { "ko", "현재 애니메이션 재생 길이\n(1000 = 1s)" }, { "jp", "現在のアニメーションの再生時間\n(1000 = 1s)" }, { "en", "Current animation play length\n(1000 = 1s)" } },
        new Dictionary<string, string> { { "ko", "현재 애니메이션 넓이" }, { "jp", "現在のアニメーションの幅" }, { "en", "Current animation width" } },
        new Dictionary<string, string> { { "ko", "현재 애니메이션 높이" }, { "jp", "現在のアニメーションの高さ" }, { "en", "Current animation height" } },
        new Dictionary<string, string> { { "ko", "현재 애니메이션 크기 비율" }, { "jp", "現在のアニメーションサイズ比率" }, { "en", "Current animation size rate" } },
        new Dictionary<string, string> { { "ko", "현재 애니메이션 바닥위치\n(우측 캔버스의 붉은 선 참조)" }, { "jp", "現在のアニメーションの底位置\n(右側キャンバスの赤線参照)" }, { "en", "Current animation bottom position\n(see red line on the right canvas)" } },
        new Dictionary<string, string> { { "ko", "캐릭터 이름을 적어주세요." }, { "jp", "キャラクター名を書いてください" }, { "en", "Write Name for character" } },
        new Dictionary<string, string> { { "ko", "이 프로그램은 무료로 사용할 수 있으며 많은 기부자들의 후원으로 제작되고 있습니다." }, { "jp", "このプログラムは無料で利用することができ、多くのパトロンの後援で制作されています。" }, { "en", "The program is free to use and is supported by many generous donors." } },
        new Dictionary<string, string> { { "ko", "클릭 반응속도" }, { "jp", "クリック反応速度 " }, { "en", "Click Reaction" } },
        new Dictionary<string, string> { { "ko", "최신" }, { "jp", "最新" }, { "en", "Latest" } },
        new Dictionary<string, string> { { "ko", "갱신가능" }, { "jp", "更新可能" }, { "en", "Updateable" } },
        new Dictionary<string, string> { { "ko", "업데이트를 위해 install.exe를 실행해주세요." }, { "jp", "アップデートのためにinstall.exeを実行してください。" }, { "en", "Run install.exe for the update." } },
        new Dictionary<string, string> { { "ko", "'idle'의 넓이로 설정합니다." }, { "jp", "'idle'の幅に設定します。" }, { "en", "Set to the width of 'idle'" } },
        new Dictionary<string, string> { { "ko", "원본의 넓이로 설정합니다." }, { "jp", "元の幅に設定します。" }, { "en", "Set to the width of the original" } },
        new Dictionary<string, string> { { "ko", "높이에 'idle'의 비율을 곱합니다." }, { "jp", "高さに'idle'の比率を掛けます。" }, { "en", "Multiply the height by the rate of 'idle'" } },
        new Dictionary<string, string> { { "ko", "'idle'의 높이로 설정합니다." }, { "jp", "'idle'の高さに設定します。" }, { "en", "Set to the height of 'idle'" } },
        new Dictionary<string, string> { { "ko", "원본의 높이로 설정합니다." }, { "jp", "元の高さに設定します。" }, { "en", "Set to the height of the original" } },
        new Dictionary<string, string> { { "ko", "넓이에 'idle'의 비율을 곱합니다." }, { "jp", "幅に'idle'の比率を掛けます。" }, { "en", "Multiply the width by the rate of 'idle'" } },
        new Dictionary<string, string> { { "ko", "추가" }, { "jp", "追加" }, { "en", "Add" } },
        new Dictionary<string, string> { { "ko", "삭제" }, { "jp", "削除" }, { "en", "Delete" } },
        new Dictionary<string, string> { { "ko", "수정" }, { "jp", "修正" }, { "en", "Edit" } },
        new Dictionary<string, string> { { "ko", "업데이트 중입니다..." }, { "jp", "アップデート中です..." }, { "en", "Under updating..." } },
        new Dictionary<string, string> { { "ko", "유저 이름" }, { "jp", "ユーザー名" }, { "en", "User name" } },
        new Dictionary<string, string> { { "ko", "UI/Setting에서 쓸 언어" }, { "jp", "UI/Settingで使う言語" }, { "en", "Languages to use in UI/Settings" } },
        new Dictionary<string, string> { { "ko", "음량" }, { "jp", "音量" }, { "en", "Volume" } },
        new Dictionary<string, string> { { "ko", "음소거" }, { "jp", "ミュート" }, { "en", "Mute" } },
        new Dictionary<string, string> { { "ko", "채팅 응답 언어\n(질문은 아무 언어나 OK)" }, { "jp", "チャット応答言語\n(質問はどの言語でもOK)" }, { "en", "Chat response language\n(Questions can be asked in any language)" } },
        new Dictionary<string, string> { { "ko", "채팅에 웹 검색 사용" }, { "jp", "チャットにWeb検索を使用" }, { "en", "Use Web search for chatting" } },
        new Dictionary<string, string> { { "ko", "좌클릭 1회로 채팅시작" }, { "jp", "左クリック1回でチャット開始" }, { "en", "Start chat with a single left click" } },
        new Dictionary<string, string> { { "ko", "키보드 키를 눌러서 채팅시작\n(클릭도 적용)" }, { "jp", "キーボードキーを押してチャット開始\n(Clickも適用)" }, { "en", "keyboard key to start chat\n(click also applies)" } },
        new Dictionary<string, string> { { "ko", "기본 대화" }, { "jp", "基本会話" }, { "en", "Default conversations" } },
        new Dictionary<string, string> { { "ko", "Web검색 결과를 대답에 반영" }, { "jp", "Web検索結果を回答に反映" }, { "en", "Web search results are reflected in the answer" } },
        new Dictionary<string, string> { { "ko", "Story 요소에 대한 대화가 가능" }, { "jp", "Story要素についての会話が可能" }, { "en", "Enables conversations about Story elements." } },
        new Dictionary<string, string> { { "ko", "AI를 이용한 번역. 리소스적으로 비추천" }, { "jp", "AIを使った翻訳。リソース的に非推奨。" }, { "en", "Translation with AI. Resourcefully not recommended." } },
        new Dictionary<string, string> { { "ko", "단기기억력. 최근 대화를 대화에 반영" }, { "jp", "短期記憶力。最近の会話を会話に反映。" }, { "en", "Short-term memory. Reflects recent conversations in the conversation." } },
        new Dictionary<string, string> { { "ko", "장기기억력. 대화를 통해 유저의 특성을 기억하고 대화에 반영" }, { "jp", "長期記憶力。会話を通じてユーザーの特性を記憶し、会話に反映。" }, { "en", "Long-term memory. It remembers user characteristics and reflects them in conversations." } },
        new Dictionary<string, string> { { "ko", "이미지 인식기능. 지정된 범위 내의 이미지나\n드래그 앤 드롭 된 이미지에 대한 대화가 가능" }, { "jp", "画像認識機能。指定された範囲内の画像や\nドラッグ＆ドロップされた画像に対する会話が可能。" }, { "en", "Image recognition. Enables conversations about images\nwithin a specified range or dragged and dropped images." } },
        new Dictionary<string, string> { { "ko", "음성 인식기능. AI와 마이크를 통해 직접 대화 가능" }, { "jp", "音声認識機能。AIとマイクで直接会話が可能" }, { "en", "Speech recognition. Enables direct conversation with AI via microphone" } },
        new Dictionary<string, string> { { "ko", "최소설정을 통한 빠른 로딩" }, { "jp", "最小設定による高速ローディング" }, { "en", "Fast loading with minimal settings" } },
        new Dictionary<string, string> { { "ko", "기본값. 모든 설정을 활성화" }, { "jp", "初期設定。すべてのオプションを起動" }, { "en", "Default. Enable all options" } },
        new Dictionary<string, string> { { "ko", "커스텀. 선택된 옵션대로 진행" }, { "jp", "カスタム。選択されたオプション通りに進行" }, { "en", "Custom. Proceed with the selected option" } },
        new Dictionary<string, string> { { "ko", "선생님, 이야기할 준비가 되었습니다." }, { "jp", "先生、話す準備はできています。" }, { "en", "I'm ready to talk, sensei." } },
        new Dictionary<string, string> { { "ko", "선생님? 대화를 시작할 수 없어요. 마이크 설정 등을 확인해주실 수 있으실까요?" }, { "jp", "先生？ 会話を始めることができません。マイクの設定などをご確認いただけますか？" }, { "en", "Sensei? I can't start a conversation. Could you please check your microphone settings or something?" } },
        new Dictionary<string, string> { { "ko", "응답에 CPU를 사용" }, { "jp", "応答にはCPUを使用。" }, { "en", "Use CPU for Normal response." } },
        new Dictionary<string, string> { { "ko", "빠른응답을 위해 Nvidia GPU 사용.\n(VRAM 약 8~10GB 필요)" }, { "jp", "高速応答のためにNvidia GPUを使用。\n(VRAM 約8～10GB必要)" }, { "en", "Use Nvidia GPU for fast response.\n(VRAM about 8~10GB needed)" } },
        new Dictionary<string, string> { { "ko", "이미 구동중입니다. 재기동하시겠습니까?" }, { "jp", "すでに稼働中です。再起動しますか？" }, { "en", "It's already running. Do you want to restart it?" } },
        new Dictionary<string, string> { { "ko", "재기동에 실패했습니다. 잠시 후 시도해주세요." }, { "jp", "再起動に失敗しました。 しばらくしてから再試行してください。" }, { "en", "Restart failed, please try again later." } },
        new Dictionary<string, string> { { "ko", "사전 로드된 모델 청소" }, { "jp", "Cleaned Preloaded Models" }, { "en", "Cleaned Preloaded Models" } }, // 일본어 번역 누락
        new Dictionary<string, string> { { "ko", "이미지 입력" }, { "jp", "画像追加" }, { "en", "Input Image" } },
        new Dictionary<string, string> { { "ko", "웹 검색" }, { "jp", "WEB検索" }, { "en", "Web Search" } },
        new Dictionary<string, string> { { "ko", "보내기" }, { "jp", "転送" }, { "en", "Send" } },
        new Dictionary<string, string> { { "ko", "Screenshot area 선택중..." }, { "jp", "Screenshot area 選択中..." }, { "en", "Selecting screenshot area..." } },
        new Dictionary<string, string> { { "ko", "Focus Mode 작동" }, { "jp", "Focus Mode 作動" }, { "en", "Focus mode activated" } },
        new Dictionary<string, string> { { "ko", "Focus Mode 해제" }, { "jp", "Focus Mode 解除" }, { "en", "Focus mode Deactivated" } },
        new Dictionary<string, string> { { "ko", "집중해서 볼게요, 선생님!" }, { "jp", "集中して見ますよ、先生！" }, { "en", "I'll focus on the focus area, sensei!" } },
        new Dictionary<string, string> { { "ko", "집중모드를 해제할게요, 선생님!" }, { "jp", "集中モードを解除します、先生！" }, { "en", "I'll turn off focus mode, sensei!" } },
        new Dictionary<string, string> { { "ko", "삭제" }, { "jp", "削除" }, { "en", "Delete" } },
        new Dictionary<string, string> { { "ko", "수정" }, { "jp", "修正" }, { "en", "Modify" } },
        new Dictionary<string, string> { { "ko", "상세" }, { "jp", "詳細" }, { "en", "Detail" } },
        new Dictionary<string, string> { { "ko", "AI 학습" }, { "jp", "AI学習 " }, { "en", "AI learning" } },
        new Dictionary<string, string> { { "ko", "현재 채팅" }, { "jp", "現在チャット" }, { "en", "Current Chat" } },
        new Dictionary<string, string> { { "ko", "새 채팅" }, { "jp", "新規チャット" }, { "en", "New Chat" } },
        new Dictionary<string, string> { { "ko", "대화 내역에서 학습할 정보를 분석합니다." }, { "jp", "会話履歴から学習する情報を分析します。" }, { "en", "Analyze the information to learn from the conversation history." } },
        new Dictionary<string, string> { { "ko", "대화 내역에서 제목 후보를 추천합니다." }, { "jp", "会話履歴からタイトル候補を推薦します。" }, { "en", "Suggest title suggestions from conversation history." } }
    };


    // 입력된 단어를 Full Scan하여 목표 언어로 번역합니다.
    // 번역할 단어, 목표 언어 
    public static string Translate(string word, string targetLang)
    {
        foreach (var entry in Texts)
        {
            if (entry.Values.Contains(word))
            {
                return entry.TryGetValue(targetLang, out var translated) ? translated : word;
            }
        }
        return word; // 번역 실패 시 원문 반환
    }
}